---

- name: Set sshd_config permissions
  become: true
  file:
    name: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600

- name: Update sshd_config
  become: true
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
  tags:
    - sshd_config

- name: Configure Password strength
  become: true
  lineinfile:
    regexp={{ item.key }}
    line={{ item.value }}
    name=/etc/security/pwquality.conf
  with_items:
    - { key: "^# minlen", value: "minlen=14" }
    - { key: "^# dcredit", value: "dcredit=-1"}
    - { key: "^# ucredit", value: "ucredit=-1"}
    - { key: "^# ocredit", value: "ocredit=-1"}
    - { key: "^# lcredit", value: "lcredit=-1"}



- name: Configure password-auth
  become: true
  lineinfile:
    name: "/etc/pam.d/password-auth"
    regexp: "^password    requisite    "
    line: "password   requisite   pam_pwquality.so try_first_pass retry=3"

- name: Configure system-auth
  become: true
  lineinfile:
    name: "/etc/pam.d/system-auth"
    regexp: "^password    requisite    "
    line: "password   requisite   pam_pwquality.so try_first_pass retry=3"

- name: Reload SSHD
  become: true
  service:
    name: sshd
    state: restarted
