---

- name: grub.conf present
  stat:
    path: /boot/grub/grub.conf
  register: grub_conf
  become: true

- name: grub.cfg present
  stat:
    path: /boot/grub2/grub.cfg
  register: grub_cfg
  become: true

- name: Change Grub Permissions and Ownership RHEL 7
  become: true

  file:
    name: /boot/grub2/grub.cfg
    owner: root
    group: root
    mode: 0600
  when: grub_cfg.stat.exists == True

- name: Change Grub Permissions and Ownership RHEL 6
  become: true

  file:
    name: /boot/grub/grub.conf
    owner: root
    group: root
    mode: 0600
  when: grub_conf.stat.exists == True